CREATE DATABASE HEALTHLINE
GO 


USE HEALTHLINE
GO 

CREATE TABLE TYPE_CATEGORY
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(50),
	META_TITLE VARCHAR(100),
	CREATE_DATE DATE,
	STATUS INT
)
GO

CREATE TABLE CATEGORY
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(50),
	META_TITLE VARCHAR(100),
	CREATE_DATE DATE,
	STATUS INT,
	TYPE_CATEGORY_ID INT REFERENCES TYPE_CATEGORY(ID)
)
GO 

CREATE TABLE POST
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(50),
	META_TITLE VARCHAR(100),
	CREATE_DATE DATE,
	STATUS INT,
	DESCRIPTION NTEXT,
	VIEWCOUNT BIGINT,
	DETAIL  NTEXT,
	AUTHOR NVARCHAR(50),
	CATEGORY_ID INT REFERENCES CATEGORY(ID)
)
GO

CREATE TABLE TAG
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(50),
	POST_ID INT REFERENCES POST(ID)
)
GO

CREATE TABLE USERS
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(50),
	STATUS INT,
	PERMISSION INT,
	IMAGE VARCHAR(100),
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50)
)
GO

CREATE TABLE USER_CATEGORY
(	
	ID INT IDENTITY(1,1) PRIMARY KEY,
	USERS_ID INT REFERENCES USERS(ID),
	TYPE_CATEGORY_ID INT REFERENCES TYPE_CATEGORY(ID) 
)
GO

CREATE TABLE FEEDBACK
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(50),
	EMAIL VARCHAR(50),
	PHONE VARCHAR(10),
	STATUS INT,
	CREATE_DATE DATE,
	CONTENT NVARCHAR(1000)
)
GO


ALTER TABLE USERS ADD IMAGE VARCHAR(100)